[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pixels = "0.11.0"
winit = "0.27.5"
winit_input_helper = "0.13.0"

[[bin]]
name = "chip8"
path = "src/bin/chip8.rs"